### ISSUE TITLE
Is Installation Broken?

### ISSUE THREAD

**Issue by Akamaozu** [flatsheet/flatsheet#60]
- Updated my fork with no issues.
- `npm install` ran successfully.
- `npm start` gets the server running, then it dies randomly.

![image](https://cloud.githubusercontent.com/assets/1587024/5423389/3b4eeefe-82bb-11e4-9713-693104337ee3.png)

Ok then. Let's try `npm bundle`. That helped before.

![image](https://cloud.githubusercontent.com/assets/1587024/5423407/52e63440-82bc-11e4-821f-9785f3eecfbe.png)

Looks like a package `flatsheet` is missing from package.json. I'll just install it.

![image](https://cloud.githubusercontent.com/assets/1587024/5423410/721da4ce-82bc-11e4-9b80-3b03a0268d54.png)

Refusing to install? How dare you, npm?! I'll show you!

- Followed the setup instructions in the README
- Still no dice

Not sure what's going on here. Is installation broken or is it just me?

**Comment by sethvincent** [comment]
This is now fixed. Current behavior: if the `.env` file doesn't exist, it will try to use `process.env` values for secret tokens & such, so the whole site won't crunch like this if the `.env` file doesn't exist.
