### ISSUE TITLE
Allow creation of a username that has already been deleted

### ISSUE THREAD

**Issue by LukeSwart** [flatsheet/flatsheet#84]
For example, if an account with username 'foo' is created, then deleted, we can no longer create another account with username 'foo'. Here is the error:

```
{ [Error: key already exists] code: 'EXISTS' }
```

Here is the output after creating and deleting an account named `foo`:

```
[lucas-ThinkPad-W520]/home/.../Flatsheet/flatsheet-dev$ superlevel data/db createReadStream
{"key":"!accounts!��paccount\u0000\u0000`�paccount\u0001\u0001plukeswart\u0001\u0001\u0001\u0001\u0000\u0000","value":"{\"admin\":true,\"email\":\"lukeswart@gmail.com\",\"username\":\"lukeswart\",\"color\":\"rgb(208, 208, 16)\"}"}
{"key":"!accounts!��paccount\u0000\u0000`�plogin\u0001\u0001pbasic\u0001\u0001pfoo\u0001\u0001\u0001\u0001\u0000\u0000","value":"{\"id\":\"9a5afa6f-3b79-4af6-a39d-f43772750a83\",\"hash\":\"55f1bd821f8385f69c2c5d3928f97efad89876d8\",\"salt\":\"19a00ed707ac215c392051c84d1be0d6\"}"}
{"key":"!accounts!��paccount\u0000\u0000`�plogin\u0001\u0001pbasic\u0001\u0001plukeswart\u0001\u0001\u0001\u0001\u0000\u0000","value":"{\"id\":\"lukeswart\",\"hash\":\"51404b40cc2c39051d80b9f0a3a2fb5cd4afbfb6\",\"salt\":\"a827d0d30fa2bbe824de3b715ea7f7f5\"}"}
{"key":"!sessions!aa71435154dcb545afd1d77ae57be74b","value":"{\"created\":\"2015-02-24T22:35:34.373Z\",\"data\":{\"username\":\"lukeswart\"}}"}
```

As you can see, although the `accountdown` key-value for 'foo' has been deleted, there is still an `accountdown-basic` account that is associated with 'foo'.

Perhaps the `accountdown` accounts and the `accountdown-basic` accounts are not being synchronized? Are we still using `body.username` as the `accountdown-basic` key?

**Comment by sethvincent** [comment]
I just realized that we need to update the version of accountdown that's being used (made an issue for it: #86).

and looking through accountdown's commits there's a chance this may be fixed by making the update.

**Comment by LukeSwart** [comment]
Thanks for the tip! I'll test this out and report back...
